pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "jsandeep9866/frontend-app"
        APP_DIR = "crud-application"
        CONTAINER_NAME = "frontend-container"
    }

    parameters {
        string(name: 'API_URL', defaultValue: 'http://localhost:9090/api/v1', description: 'Backend API URL')
    }

    stages {

        stage('Clone Repo') {
            steps {
                deleteDir()
                git branch: 'main', url: 'https://github.com/17pa1a0447-tech/Frontendcode.git'
            }
        }

        stage('Replace API URL') {
            steps {
                sh """
                    sed -i 's#__API_URL__#${params.API_URL}#g' ${APP_DIR}/src/environments/environment.prod.ts
                """
            }
        }

        stage('Build Angular App') {
            steps {
                dir("${APP_DIR}") {
                    sh 'npm install'
                    sh 'npm run build -- --configuration=production'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} -t ${DOCKER_IMAGE}:latest ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jsandeep9866',
                        usernameVariable: 'USER', passwordVariable: 'PASS')]) {

                    sh '''
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                        docker push ${DOCKER_IMAGE}:latest
                        docker logout
                    '''
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                    docker rm -f frontend-container || true
                    docker run -d -p 3025:80 --name frontend-container jsandeep9866/frontend-app:latest
                '''
            }
        }
    }

    post {
        success {
            echo "Frontend deployed successfully!"
        }
        failure {
            echo "Frontend pipeline failed!"
        }
    }
}
